### PR TITLE
Moving 'legacy' add-on content into a new section in the add-on sidebar

### PR DESCRIPTION
**Pull request by rebloor**

### CODE REVIEW

**Comment by rebloor** [comment]
Hi Will, 
I wasn't aware of the ability to test macro changes - I'll get that set up and test out some options. And sorry for not including a detailed description - I assume that we had discussed and understood the change earlier - sorry, a poor assumption. Not sure what you mean by "Also this patch doesn't apply cleanly on master." can you clarify?

**Comment by wbamberg** [comment]
> I wasn't aware of the ability to test macro changes

Yes, you can set up your own local version of Kuma to test macro changes. Please ask if you have any problems getting it working.

I know the sidebar macro is not at all easy to work with, so being able to experiment with it helps a lot.

> And sorry for not including a detailed description - I assume that we had discussed and understood the change earlier

We did, but there are lots of conversations happening with lots of people across lots of systems - Bugzilla, GitHub, Taiga, Trello, email, Vidyo, IRC, gdoc - it's completely beyond me to keep that whole web in my head, so it's hard for me to know that a particular PR is connected with a particular gdoc comment. So writing down what a particular PR is intended to do, and why, saves me a lot of time trying to understand it from the code and map it onto a conversation. It also means that in theory, people who aren't me can review it.

> Not sure what you mean by "Also this patch doesn't apply cleanly on master." can you clarify?

Sure. You've branched the KumaScript macros and applied some changes to AddonSidebar.ejs. But in the time since you branched them, some new changes have been made to the master copy of AddonSidebar.ejs. GitHub thinks that the new changes conflict with the changes that you've made, so we can't automatically merge your changes: you need to resolve the conflicts between your updated version and the updated version in master.

If I were you, I'd probably stash a copy of your changes, then just check out the new master, then manually reapply your changes on it.

**Comment by rebloor** [comment]
Hi Will,

Setting up the 'test' mechanism now. And sorry, guess I need to be more appreciative of the pies you have fingers in :-) And stashing - and closing this pull - I'll create a new hopefully clean, well-described one once I 've tested the changes.

**Comment by wbamberg** [comment]
Thanks @rebloor !

**Pull request closed without merging**
