### PR TITLE
updates so "make lint" runs clean

### PR DESCRIPTION
**Pull request by escattone**
Changes so that ``make lint`` runs clean.

### CODE REVIEW

**Comment by escattone** [comment]
Now that #223 has merged, I'm going to rebase this on master.

**Comment by escattone** [comment]
Great question, yes I think so.

**Comment by escattone** [comment]
If you're OK with that, I'll add it to the Travis and Jenkins builds.

**Comment by jwhitlock** [comment]
Yes please. I am a fan of robots being jerks to enforce rules.

**Pull request merged**
