### PR TITLE
Edits to include Android in Legacy Notice

### PR DESCRIPTION
**Pull request by andrewtruongmoz**
Including Android in legacy notice and to make it more clear. Per issue #167

### CODE REVIEW

**Comment by andrewtruongmoz** [comment]
@atsay @wbamberg for checking

**Comment by wbamberg** [comment]
The different way Firefox for Android is mentioned in the two \<strong\> paragraphs reads weirdly to me:

    "Starting from Firefox 53, no new legacy add-ons will be accepted on
    addons.mozilla.org (AMO) for desktop Firefox and Firefox for Android."



    "Starting from Firefox 57, WebExtensions will be the only supported
    extension type, and Firefox will not load other types. This affects
    desktop Firefox and Firefox for Android."

Why not make the second follow the same pattern as the first:

    "Starting from Firefox 57, WebExtensions will be the only supported
    extension type. Desktop Firefox and Firefox for Android will not load
    other extension types."

?

**Comment by atsay** [comment]
Wfm

**Comment by wbamberg** [comment]
Thanks @andrewtruongmoz !

**Pull request merged**
