### PR TITLE
bug 1189118 - Upgrade kumascript for node 0.10.36

### PR DESCRIPTION
**Pull request by darkwing**
First step toward upgrade. To test:
1.  Install nvm and use node v 0.10.36
2.  `npm rebuild`
3.  `./node_modules/.bin/nodeunit tests`

What concerns me is needing to `npm rebuild` instead of just `npm install` which travis does.  `memcached` is the culprit.

### CODE REVIEW

**Comment by darkwing** [comment]
Oddly enough, if I `rm -rf node_modules/`, then do `npm install`, everything installs fine.  :/

**Comment by darkwing** [comment]
Important update is making travis run `npm rebuild` instead of just `install`.  This is important when making updates that contain binaries.

**Comment by groovecoder** [comment]
Nice update.

**Comment by darkwing** [comment]
Now that I know we use RPM on stage and prod, I'll want to rethink the rebuild part of travis; could lead to problem :/

**Comment by darkwing** [comment]
To Do:

-  Add `memcached` to the git-ignore
-  Change travis back to `.travis.yml`

**Comment by escattone** [comment]
This is superseded by PR 69 (https://github.com/mozilla/kumascript/pull/69).

**Pull request closed without merging**
