### PR TITLE
adding learning area links to main HTML sidebar

### PR DESCRIPTION
**Pull request by chrisdavidmills**
This PR adds learning area links to the main HTML sidebar.

### CODE REVIEW

**Comment by Elchi3** [comment]
This throws due to missing variables and functions.

- Please  add `var learnBaseURL = "/" + locale + "/docs/Learn/";` and rename `baseURL` to `learnBaseURL`.
- Please remove `currentPageIsUnder` calls as this won't happen for Learn/ pages (HTML sidebar browses under HTML/) Just remove the `data-default-state` attribute completely.

**Comment by Elchi3** [comment]
Note: @SphinxKnight is updating this for French l10n strings. Please wait for that before merging this.

**Comment by Elchi3** [comment]
@SphinxKnight @chrisdavidmills Do you two manage to merge Sphinx's changes into this PR? If not we can merge what Chris has here and Sphinx opens a new one?

**Comment by SphinxKnight** [comment]
I have the changes available for another PR if necessary.

**Comment by Elchi3** [comment]
@SphinxKnight Please open a new PR for the French translation. (your current branch needs to be rebased now)

**Pull request merged**
