### PR TITLE
Add Dockerfile and Makefile

### PR DESCRIPTION
**Pull request by jgmize**
@jwhitlock r?

### CODE REVIEW

**Comment by jwhitlock** [comment]
What do you want out of a review?

**Comment by jgmize** [comment]
> What do you want out of a review?

1. Install docker
2. `make build`
3. `make test`
4. `make run`
5. verify that running kumascript service works as expected on port 9080.

**Comment by jwhitlock** [comment]
Failed on ``make build``: https://pastebin.mozilla.org/8870483

**Comment by jgmize** [comment]
@jwhitlock that was just a network glitch: `Failed to fetch http://httpredir.debian.org/debian/pool/main/n/node-read/node-read_1.0.5-1_all.deb  Error reading from server. Remote end closed connection` -- would you mind trying again?

**Comment by jwhitlock** [comment]
[Next ran passed](https://pastebin.mozilla.org/8870494). Moving on...

**Comment by jwhitlock** [comment]
Failed on ``make test``: https://pastebin.mozilla.org/8870495

**Comment by jgmize** [comment]
thanks @jwhitlock, it was passing locally b/c I ran `npm install` while the app dir was mounted against my local machine, which installed them into `node_modules` on the host machine, which were then being used during `make test`. I've added https://github.com/mozilla/kumascript/pull/56/commits/c146eae05858a168b14704a194cff78139d5952c so that it will use `/node_modules` within the container instead.

**Comment by jwhitlock** [comment]
``make test`` works now.

In the development environment, you'd make a request like this to render the content of https://developer-local.allizom.org/en-US/docs/Mozilla:

```
curl  http://localhost:9080/docs/en-US/Mozilla
```

When running this against Docker, I get:

```
curl: (7) Failed to connect to localhost port 9080: Connection refused
```
There is no logging output from the ``make run`` command.

The other production difference is that we create a ``kumascript_settings_local.json`` file, with something like:

```
{
    "log": {
        "console": true,
        "file": {
            "filename": "/home/vagrant/logs/kumascript.log",
            "maxsize": 500000
        }
    },
    "server": {
        "port": 9080,
        "numWorkers": 4,
        "workerTimeout": 10000,
        "memcache": {
            "server": {"127.0.0.1:11211": 1},
            "options": { }
        },
        "macro_timeout": 60000,
        "document_url_template": "https://localhost/en-US/docs/{path}?raw=1",
        "template_url_template": "https://localhost/en-US/docs/en-US/Template:{name}?raw=1",
        "template_class": "EJSTemplate",
        "autorequire": {
            "mdn": "MDN:Common",
            "Date": "DekiScript:Date",
            "Page": "DekiScript:Page",
            "String": "DekiScript:String",
            "Uri": "DekiScript:Uri",
            "Web": "DekiScript:Web",
            "Wiki": "DekiScript:Wiki"
        }
    }
}
```
I don't know if any effort has been made to instead get config variables from the environment.  The code suggests port ``9000`` is the default in [one place](https://github.com/mozilla/kumascript/blob/master/lib/kumascript/server.js#L45), and ``9080`` in [another place](https://github.com/mozilla/kumascript/blob/master/lib/kumascript/conf.js#L30).

**Comment by jgmize** [comment]
> curl  http://localhost:9080/docs/en-US/Mozilla
> When running this against Docker, I get:
> curl: (7) Failed to connect to localhost port 9080: Connection refused

The localhost port mapping works in linux and in the latest docker for mac beta (I recommend [signing up](https://beta.docker.com/) for it if you haven't already), but assuming you're using the current release of docker-toolbox then you'll need to connect to the virtualbox vm's ip on that port, which can be obtained with `docker-machine ip`. 

Locally for me, `make run` followed by `curl  http://localhost:9080/docs/en-US/Mozilla` in another shell gives me:
```
<p>The articles below include content about downloading and building Mozilla code. In addition, you'll find helpful articles about how the code works, how to build add-ons for Mozilla applications and the like.</p>

<p><p><strong>There are no subpages at this time.</strong></p></p>
```

> I don't know if any effort has been made to instead get config variables from the environment.

I haven't made any in this PR, but we can and should follow up on that after this PR lands.

**Comment by jwhitlock** [comment]
``docker-machine ip default`` gives ``192.168.99.100``, and ``curl http://192.168.99.100/docs/en-US/Mozilla`` gives the same response.  It appears to be talking to production, since giving a recent page path ``curl http://192.168.99.100:9080/docs/id/Web/CSS`` gives the content of a [page created today](https://developer.mozilla.org/id/docs/Web/CSS).

+r, merge when ready.

**Comment by groovecoder** [comment]
FWIW, I had [a commit on the heroku branch](https://github.com/mozilla/kumascript/commit/9279bfcb14953f579538141d28314f4f2bd188cb) that made kumascript listen to process.env.port.

Our [`nconf` module](https://www.npmjs.com/package/nconf) should be able to use environment variables for config values, but it seems like I had trouble getting the env vars to work?

**Pull request merged**
