### PR TITLE
Adding Gamepad Extensions spec to SpecName/Spec2

### PR DESCRIPTION
**Pull request by chrisdavidmills**
This API covers stuff like getting haptic feedback from controllers, and pose information from WebVR controllers

### CODE REVIEW

**Comment by Elchi3** [comment]
I don't understand the travis failure. Setting @escattone as a reviewer :)

**Comment by chrisdavidmills** [comment]
Cool stuff - I've had a look at the Travis details, and don't have as clue what that is ;-)

**Comment by jwhitlock** [comment]
TravisCI updated their [images](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch). I tested Kuma (https://github.com/mozilla/kuma/pull/4278), but neglected testing Kumascript.

**Comment by jwhitlock** [comment]
I think this is OK to merge w/ @Elchi3's review, despite the test failure. Alternatively, the fix will be in a different PR, and you can rebase on top when that is merged.

**Pull request merged**
