### PR TITLE
Updated the macros that generate WebExtension compat tables from JSON…

### PR DESCRIPTION
**Pull request by wbamberg**
… data.

This updates three macros: WebExtBrowserCompat.ejs, WebExtBrowserCompatTable.ejs, WebExtAllCompatTables.ejs, and removes one: WebExtBrowserCompatSummaryTable.ejs.

Of the three updated macros:

* WebExtBrowserCompatTable.ejs is the one that does the work of generating tables (both aggregate tables for collections of "features", such as "bookmarks", and detailed tables for individual features, such as "bookmarks.create()"). It's only called by the other two macros: WebExtBrowserCompat.ejs and WebExtAllCompatTables.ejs.

* WebExtBrowserCompat.ejs is the macro you put in API reference pages, to build and insert a table appropriate to the including page. To see what the output looks like, add {{WebExtBrowserCompat}} to an API reference page under /en-US/Add-ons/WebExtensions/API/, like:

/en-US/Add-ons/WebExtensions/API/alarms
/en-US/Add-ons/WebExtensions/API/alarms/clear
/en-US/Add-ons/WebExtensions/API/devtools.inspectedWindow
/en-US/Add-ons/WebExtensions/API/devtools.inspectedWindow/eval
/en-US/Add-ons/WebExtensions/API/devtools.inspectedWindow
/en-US/Add-ons/WebExtensions/API/webRequest
/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired

* WebExtAllCompatTables.ejs can be inserted anywhere and generates all the aggregate tables. It's used to build https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs.

The removed macro, WebExtBrowserCompatSummaryTable.ejs, is no longer used.

This turned out to be a bigger change than I'd anticipated. But I've tried to keep the tables pretty similar to the way they were before. The biggest change is that I've gone back to using footnotes for notes, as that seems to work better now we don't use notes for everything.

### CODE REVIEW

**Comment by Elchi3** [comment]
I have created a whole lot of WebExtension pages locally and I never ran into a KumaScript error. I looked at different pages: overview page, api main page, api sub page, api sub page with subfeatures, and pages with footnotes.

Overall the code looks solid and makes nice use of ES6 features. It is also well commented.

I don't like the URL hackery in WebExtBrowserCompat.ejs to retrieve the correct data on the correct page (especially since there are extra cases like the devtools namespace). I think a macro that works across all domains and that takes an identifier would be more compelling to me in the future (ala `{{compat("webextensions.api.alarms.clear")}}` and `{{compat("css.properties.clear")}}` etc.). That would mean that you would need to update all pages, so let's do that only when we think there is a chance to introduce a common BC macro. To have one macro we also need a single table design. WebExtensions use their own table design at the moment. So, I think there is more work to this. All this said, lets use the URL hackery for now.

Locally, the table cells have the classes `.full-support `etc. but they weren't actually green for me. Maybe my local CSS isn't up-to-date. Can you double check with latest kuma master if this works for you?

I've tested a few pages with footnotes and they look good to me. In fact, with the sub features, the section is much more concise and faster to grasp for me. 

I'm not sure how to test this harder, we will likely hit edge cases when we deploy this all over the WebExtension pages?!

**Comment by stephaniehobson** [comment]
Zone work deleted the cell colours for a day, sorry! Update from master and you should have the cell colours again.

**Comment by Elchi3** [comment]
Confirming that the CSS works indeed after these steps:
- I updated Kuma to master
- I ran `manage.py migrate` and  `make build-static` in the `kuma_web_1` container.

Tables have correct CSS and this looks good to me overall. Let's try and get this deployed today.

**Comment by jwhitlock** [comment]
This is in staging and production.  This page seems OK:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/alarms/clear

There's a KS error on:

https://developer.mozilla.org/en-US/docs/Archive/Add-ons/bookmarks.export

There may need to be follow-on work for this macro when use on an /Archive/ page.

**Comment by wbamberg** [comment]
> There's a KS error on:
> 
> https://developer.mozilla.org/en-US/docs/Archive/Add-ons/bookmarks.export
> 
> There may need to be follow-on work for this macro when use on an /Archive/ page.

The current macros are designed so you can just call them with no arguments and have them figure out what data to use for the compat tables. This means you can have the same macro call on every API page (which was very handy when I was generating the original pages). But that makes them sensitive to their location. In this case they're moved out of the `Add-ons/WebExtensions/API` hierarchy, and the error generated is actually an attempt provide a helpful diagnostic:

`This macro can only be called from pages under "Add-ons/WebExtensions/API/"`

So I do think this is working as expected (if the page move had preserved the original hierarchy, the call would have worked). In this particular case, I have removed the compat data for `bookmarks.export` and `bookmarks.import`, so the links no longer appear in the [`bookmarks` aggregate table](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks#Browser_compatibility), and removed the macro calls from the archived pages, so the errors no longer appear.

Florian makes the point that it would be better for these macros not to figure out their data from their URLs, and I tend to agree, but that would involve editing all 400-odd pages under WebExtensions/API, so I would prefer to wait for that until we have a common macro for all compat tables.

**Pull request merged**
